const industryList = {
    'AIR': 'Airlines',
    'ALU': 'Aluminium',
    'ARO': 'Aerospace & Defense',
    'ATX': 'Auto Components',
    'AUT': 'Automobiles',
    'BLD': 'Building Products',
    'BNK': 'Banks',
    'BTC': 'Biotechnology',
    'BVG': 'Beverages',
    'CHM': 'Chemicals',
    'CMT': 'Communications Equipment',
    'CNO': 'Casinos & Gambling',
    'COL': 'Coal & Consumable Fuels',
    'COM': 'Construction Materials',
    'CON': 'Construction & Engineering',
    'COS': 'Personal Products',
    'CSV': 'Diversified Consumer Services',
    'CTR': 'Containers & Packaging',
    'DHP': 'Household Durables',
    'DRG': 'Pharmaceuticals',
    'ELC': 'Electric Utilities',
    'ELQ': 'Electrical Components & Equipment',
    'FBN': 'Diversified Financial Services & Capital Markets',
    'FDR': 'Food & Staples Retailing',
    'FOA': 'Food Products',
    'FRP': 'Paper & Forest Products',
    'GAS': 'Gas Utilities',
    'HEA': 'Health Care Providers & Services',
    'HOM': 'Homebuilding',
    'HOU': 'Household Products',
    'ICS': 'Commercial Services & Supplies',
    'IDD': 'Industrial Conglomerates',
    'IEQ': 'Machinery & Electrical Equipment',
    'IMS': 'Interactive Media, Services & Home Entertainment',
    'INS': 'Insurance',
    'ITC': 'Electronic Equipemnt, Instruments & Components',
    'LEG': 'Leisure Equipment, Products & Consumer Electronics',
    'LIF': 'Life Sciences Tools & Equipment',
    'MNX': 'Metals & Mining',
    'MTC': 'Health Care Equipment & Supplies',
    'MUW': 'Multi and Water Utilities',
    'OGR': 'Oil & Gas Refining & Marketing',
    'OGX': 'Oil & Gas Upstream & Integrated',
    'OIE': 'Energy Equipment & Services',
    'PIP': 'Oil & Gas Storage & Transportation',
    'PRO': 'Professional Services',
    'PUB': 'Media, Movies & Entertainment',
    'REI': 'Equity Real Estate Investment Trusts',
    'REM': 'Real Estate Management & Development',
    'REX': 'Restaurants & Leisure Facilities',
    'RTS': 'Retailing',
    'SEM': 'Semiconductors & Semiconductor Equipment',
    'SOF': 'Software',
    'STL': 'Steel',
    'TCD': 'Trading Companies & Distributors',
    'TEX': 'Textiles, Apparel & Luxury Goods',
    'THQ': 'Computers & Peripherals and Office Electronics',
    'TLS': 'Telecommunication Services',
    'TOB': 'Tobacco',
    'TRA': 'Transportation and Transportation Infrastructure',
    'TRT': 'Hotels, Resorts & Cruise Lines',
    'TSV': 'IT Services',
};

export {industryList};