const industryList = {
    'Airlines': 'AIR',
    'Aluminium': 'ALU',
    'Aerospace & Defense': 'ARO',
    'Auto Components': 'ATX',
    'Automobiles': 'AUT',
    'Building Products': 'BLD',
    'Banks': 'BNK',
    'Biotechnology': 'BTC',
    'Beverages': 'BVG',
    'Chemicals': 'CHM',
    'Communications Equipment': 'CMT',
    'Casinos & Gambling': 'CNO',
    'Coal & Consumable Fuels': 'COL',
    'Construction Materials': 'COM',
    'Construction & Engineering': 'CON',
    'Personal Products': 'COS',
    'Diversified Consumer Services': 'CSV',
    'Containers & Packaging': 'CTR',
    'Household Durables': 'DHP',
    'Pharmaceuticals': 'DRG',
    'Electric Utilities': 'ELC',
    'Electrical Components & Equipment': 'ELQ',
    'Diversified Financial Services & Capital Markets': 'FBN',
    'Food & Staples Retailing': 'FDR',
    'Food Products': 'FOA',
    'Paper & Forest Products': 'FRP',
    'Gas Utilities': 'GAS',
    'Health Care Providers & Services': 'HEA',
    'Homebuilding': 'HOM',
    'Household Products': 'HOU',
    'Commercial Services & Supplies': 'ICS',
    'Industrial Conglomerates': 'IDD',
    'Machinery & Electrical Equipment': 'IEQ',
    'Interactive Media, Services & Home Entertainment': 'IMS',
    'Insurance': 'INS',
    'Electronic Equipemnt, Instruments & Components': 'ITC',
    'Leisure Equipment, Products & Consumer Electronics': 'LEG',
    'Life Sciences Tools & Equipment': 'LIF',
    'Metals & Mining': 'MNX',
    'Health Care Equipment & Supplies': 'MTC',
    'Multi and Water Utilities': 'MUW',
    'Oil & Gas Refining & Marketing': 'OGR',
    'Oil & Gas Upstream & Integrated': 'OGX',
    'Energy Equipment & Services': 'OIE',
    'Oil & Gas Storage & Transportation': 'PIP',
    'Professional Services': 'PRO',
    'Media, Movies & Entertainment': 'PUB',
    'Equity Real Estate Investment Trusts': 'REI',
    'Real Estate Management & Development': 'REM',
    'Restaurants & Leisure Facilities': 'REX',
    'Retailing': 'RTS',
    'Semiconductors & Semiconductor Equipment': 'SEM',
    'Software': 'SOF',
    'Steel': 'STL',
    'Trading Companies & Distributors': 'TCD',
    'Textiles, Apparel & Luxury Goods': 'TEX',
    'Computers & Peripherals and Office Electronics': 'THQ',
    'Telecommunication Services': 'TLS',
    'Tobacco': 'TOB',
    'Transportation and Transportation Infrastructure': 'TRA',
    'Hotels, Resorts & Cruise Lines': 'TRT',
    'IT Services': 'TSV',
};

export {industryList};